# Generated by Django 4.2.30 on 2026-05-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
