# Generated by Django 6.0.5 on 2026-05-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
